targets:
  $default:
    builders:
      eliud_generator|simple:
        enabled: true

builders:
  simple:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["simple"]
    build_extensions: {'.spec':['.g.dart']}
    build_to: source
    auto_apply: all_packages
