targets:
  $default:
    builders:
      eliud_generator|model:
        enabled: true
      eliud_generator|entity:
        enabled: true
      eliud_generator|repository:
        enabled: true
      eliud_generator|firestore:
        enabled: true
      eliud_generator|component_event:
        enabled: true
      eliud_generator|component_state:
        enabled: true
      eliud_generator|component_bloc:
        enabled: true
      eliud_generator|component:
        enabled: true
      eliud_generator|internal_component:
        enabled: true
      eliud_generator|repository_singleton:
        enabled: true
      eliud_generator|abstarct_repository_singleton:
        enabled: true
      eliud_generator|component_registry:
        enabled: true
      eliud_generator|admin_app:
        enabled: true

builders:
  model:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["model"]
    build_extensions: {".spec": ["_model.dart"]}
    build_to: source
    auto_apply: all_packages

  entity:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["entity"]
    build_extensions: {".spec": ["_entity.dart"]}
    build_to: source
    auto_apply: all_packages

  repository:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["repository"]
    build_extensions: {".spec": ["_repository.dart"]}
    build_to: source
    auto_apply: all_packages

  cache:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["cache"]
    build_extensions: {".spec": ["_cache.dart"]}
    build_to: source
    auto_apply: all_packages

  firestore:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["firestore"]
    build_extensions: {".spec": ["_firestore.dart"]}
    build_to: source
    auto_apply: all_packages

  component_event:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["component_event"]
    build_extensions: {".spec": ["_component.event.dart"]}
    build_to: source
    auto_apply: all_packages

  component_state:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["component_state"]
    build_extensions: {".spec": ["_component_state.dart"]}
    build_to: source
    auto_apply: all_packages

  component_bloc:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["component_bloc"]
    build_extensions: {".spec": ["_component_bloc.dart"]}
    build_to: source
    auto_apply: all_packages

  component:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["component"]
    build_extensions: {".spec": ["_component.dart"]}
    build_to: source
    auto_apply: all_packages

  list_event:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["list_event"]
    build_extensions: {".spec": ["_list_event.dart"]}
    build_to: source
    auto_apply: all_packages

  list_state:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["list_state"]
    build_extensions: {".spec": ["_list_state.dart"]}
    build_to: source
    auto_apply: all_packages

  list_bloc:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["list_bloc"]
    build_extensions: {".spec": ["_list_bloc.dart"]}
    build_to: source
    auto_apply: all_packages

  list:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["list"]
    build_extensions: {".spec": ["_list.dart"]}
    build_to: source
    auto_apply: all_packages

  dropdown_button:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["dropdown_button"]
    build_extensions: {".spec": ["_dropdown_button.dart"]}
    build_to: source
    auto_apply: all_packages

  component_selector:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["component_selector"]
    build_extensions: {".spec": ["_component_selector.dart"]}
    build_to: source
    auto_apply: all_packages

  form_event:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["form_event"]
    build_extensions: {".spec": ["_form_event.dart"]}
    build_to: source
    auto_apply: all_packages

  form_state:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["form_state"]
    build_extensions: {".spec": ["_form_state.dart"]}
    build_to: source
    auto_apply: all_packages

  form_bloc:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["form_bloc"]
    build_extensions: {".spec": ["_form_bloc.dart"]}
    build_to: source
    auto_apply: all_packages

  form:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["form"]
    build_extensions: {".spec": ["_form.dart"]}
    build_to: source
    auto_apply: all_packages

  internal_component:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["internal_component"]
    build_extensions: {r"$lib$": ["internal_component.dart"]}
    build_to: source
    auto_apply: all_packages

  embedded_component:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["embedded_component"]
    build_extensions: {r"$lib$": ["embedded_component.dart"]}
    build_to: source
    auto_apply: all_packages

  repository_singleton:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["repository_singleton"]
    build_extensions: {r"$lib$": ["repository_singleton.dart"]}
    build_to: source
    auto_apply: all_packages

  abstract_repository_singleton:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["abstract_repository_singleton"]
    build_extensions: {r"$lib$": ["abstract_repository_singleton.dart"]}
    build_to: source
    auto_apply: all_packages

  admin_app:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["admin_app"]
    build_extensions: {r"$lib$": ["admin_app.dart"]}
    build_to: source
    auto_apply: all_packages

  repository_export:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["repository_export"]
    build_extensions: {r"$lib$": ["repository_export.dart"]}
    build_to: source
    auto_apply: all_packages

  cache_export:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["cache_export"]
    build_extensions: {r"$lib$": ["cache_export.dart"]}
    build_to: source
    auto_apply: all_packages

  entity_export:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["entity_export"]
    build_extensions: {r"$lib$": ["entity_export.dart"]}
    build_to: source
    auto_apply: all_packages

  model_export:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["model_export"]
    build_extensions: {r"$lib$": ["model_export.dart"]}
    build_to: source
    auto_apply: all_packages

  component_registry:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["component_registry"]
    build_extensions: {r"$lib$": ["component_registry.dart"]}
    build_to: source
    auto_apply: all_packages

