targets:
  $default:
    builders:
      eliud_generator|model:
        enabled: true
      eliud_generator|entity:
        enabled: true
      eliud_generator|repository:
        enabled: true
      eliud_generator|firestore:
        enabled: true
      eliud_generator|event:
        enabled: true
      eliud_generator|state:
        enabled: true
      eliud_generator|bloc:
        enabled: true

builders:
  model:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["model"]
    build_extensions: {".spec": [".model.dart"]}
    build_to: source
    auto_apply: all_packages

  entity:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["entity"]
    build_extensions: {".spec": [".entity.dart"]}
    build_to: source
    auto_apply: all_packages

  repository:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["repository"]
    build_extensions: {".spec": [".repository.dart"]}
    build_to: source
    auto_apply: all_packages

  event:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["event"]
    build_extensions: {".spec": [".event.dart"]}
    build_to: source
    auto_apply: all_packages

  state:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["state"]
    build_extensions: {".spec": [".state.dart"]}
    build_to: source
    auto_apply: all_packages

  bloc:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["bloc"]
    build_extensions: {".spec": [".bloc.dart"]}
    build_to: source
    auto_apply: all_packages

  firestore:
    target: ":eliud_generator"
    import: "package:eliud_generator/builder.dart"
    builder_factories: ["firestore"]
    build_extensions: {".spec": [".firestore.dart"]}
    build_to: source
    auto_apply: all_packages
