name: eliud_generator
description: Eliud Code Generator

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  equatable: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: "2.1.2"
  analyzer: 1.5.0

flutter:
  uses-material-design: true
