name: eliud_generator
description: Eliud Code Generator

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  eliud_annotations:
    path: ../eliud_annotations
  build: "1.2.2"
  source_gen: "0.9.4+6"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "1.7.2"

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: io.eliud.eliud_generator
    iosBundleIdentifier: io.eliud.eliudGenerator
