name: eliud_generator
description: Eliud Code Generator

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  build: "1.2.2"
  json_schema: 2.2.1
  equatable: ^1.0.0
  path_provider: 1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "1.7.2"

flutter:
  uses-material-design: true
