name: eliud_generator
description: Eliud Code Generator
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_generator

version: 1.0.2

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.5
  build: ^2.1.0
  path: ^1.8.2
  glob: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.0
  analyzer: 1.5.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
