---
name: eliud_generator
description: "Eliud Code Generator is used by most eliud packages to generates models,\
  \ entities, repositories, blocs, components, etc based on details in spec files."
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_generator
version: 1.1.5+6
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  equatable: ^2.0.5
  build: ^2.1.0
  path: ^1.8.2
  glob: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  analyzer: ^6.2.0
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
