---
name: eliud_generator
description: "Eliud Code Generator is used by most eliud packages to generates models,\
  \ entities, repositories, blocs, components, etc based on details in spec files."
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_generator
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  equatable: ^2.0.5
  build: ^2.4.1
  path: ^1.9.0
  glob: ^2.1.2
dev_dependencies:
  build_runner: ^2.4.7
  analyzer: ^6.3.0
  lints: ^5.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
