---
name: eliud_generator
description: "Eliud Code Generator is used by most eliud packages to generates models,\
  \ entities, repositories, blocs, components, etc based on details in spec files."
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_generator
version: 1.1.6
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  equatable: ^2.0.5                                                                                  # ANDROID IOS LINUX MACOS WEB WINDOWS
  build: ^2.4.1                                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS
  path: ^1.8.3                                                                                       # ANDROID IOS LINUX MACOS WEB WINDOWS
  glob: ^2.1.2                                                                                       # ANDROID IOS LINUX MACOS WEB WINDOWS

dev_dependencies:
  build_runner: ^2.4.7                                                                               # ANDROID IOS LINUX MACOS WEB WINDOWS
  analyzer: ^6.3.0                                                                                   # ANDROID IOS LINUX MACOS WEB WINDOWS
  lints: ^3.0.0                                                                                      # ANDROID IOS LINUX MACOS WEB WINDOWS

flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
